/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTabbar: typeof import('./src/components/AppTabbar.vue')['default']
    BaseTab: typeof import('./src/components/BaseTab.vue')['default']
    BaseTabbar: typeof import('./src/components/Tabbar/BaseTabbar.vue')['default']
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    DataStatistics: typeof import('./src/components/PersonalCard/DataStatistics.vue')['default']
    DrawerContent: typeof import('./src/components/DrawerContent.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    MainCard: typeof import('./src/components/MainCard.vue')['default']
    PersonalCard: typeof import('./src/components/PersonalCard/PersonalCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/Tabbar/SearchBar.vue')['default']
    SocialChannels: typeof import('./src/components/PersonalCard/SocialChannels.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    TabNotification: typeof import('./src/components/Tabbar/TabNotification.vue')['default']
    TestAutoImport: typeof import('./src/components/TestAutoImport.vue')['default']
    UserMenu: typeof import('./src/components/Tabbar/UserMenu.vue')['default']
  }
}
